import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import AuthCard from '../../components/auth/AuthCard';
import { completePasswordReset, requestPasswordReset, verifyPasswordReset } from '../../lib/auth/authService';

export default function PasswordRecoveryPage() {
  const navigate = useNavigate(); const [token, setToken] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [stage, setStage] = useState('request'); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { const value = new URLSearchParams(window.location.search).get('token_hash') || ''; if (value) { setToken(value); setStage('verify'); window.history.replaceState({}, '', '/auth/reset-password'); } }, []);
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { if (stage === 'request') { await requestPasswordReset(email); setNotice('If an account matches that email, check your inbox for recovery instructions.'); } else if (stage === 'verify') { await verifyPasswordReset(token); setStage('complete'); } else { await completePasswordReset(password); navigate('/login', { replace: true }); } } catch (reason) { setError(reason.message || 'Unable to complete password recovery.'); } finally { setBusy(false); } };
  return <AuthCard title="Password recovery" description="Recovery links are confirmed explicitly and cannot open the app dashboard."><form onSubmit={submit} className="space-y-4">{stage === 'request' ? <input required type="email" autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Email" className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" /> : null}{stage === 'verify' ? <p className="text-sm text-slate-600">Verify this recovery link before choosing a password.</p> : null}{stage === 'complete' ? <input required type="password" minLength="15" autoComplete="new-password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="New password (15+ characters)" className="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm" /> : null}{notice ? <p className="text-xs font-semibold text-emerald-700">{notice}</p> : null}{error ? <p role="alert" className="text-xs font-semibold text-rose-600">{error}</p> : null}<button disabled={busy || (stage === 'verify' && !token)} className="w-full rounded-xl bg-indigo-600 px-4 py-3 text-sm font-bold text-white disabled:opacity-60">{busy ? 'Please wait…' : stage === 'request' ? 'Send recovery email' : stage === 'verify' ? 'Verify recovery link' : 'Set new password'}</button><Link to="/login" className="block text-center text-xs font-bold text-indigo-600">Back to sign in</Link></form></AuthCard>;
}
